export {
    ABOUT_CONTENT_OUR_MEMBER,
    ABOUT_CONTENT_OUR_WORK,
    ABOUT_CONTENT_START,
    ABOUT_CONTENT_MIDDLE,
    CATEGORIES_ITEM,
    PRODUCTS_ITEM,
    ITEM_CAROUSEL,
    HEADER_MENU,
    FORM_FILTER,
    STATISTICS,
    SHOPPING_CART,
} from './Text'